package oracle.adf.research.model.bc.entity;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 15 00:53:44 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AwardProfessorEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AwardProfessorId,
        AwardId,
        ProfessorId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int AWARDPROFESSORID = AttributesEnum.AwardProfessorId.index();
    public static final int AWARDID = AttributesEnum.AwardId.index();
    public static final int PROFESSORID = AttributesEnum.ProfessorId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AwardProfessorEOImpl() {
    }

    /**
     * Gets the attribute value for AwardProfessorId, using the alias name AwardProfessorId.
     * @return the value of AwardProfessorId
     */
    public Number getAwardProfessorId() {
        return (Number) getAttributeInternal(AWARDPROFESSORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AwardProfessorId.
     * @param value value to set the AwardProfessorId
     */
    public void setAwardProfessorId(Number value) {
        setAttributeInternal(AWARDPROFESSORID, value);
    }

    /**
     * Gets the attribute value for AwardId, using the alias name AwardId.
     * @return the value of AwardId
     */
    public Number getAwardId() {
        return (Number) getAttributeInternal(AWARDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AwardId.
     * @param value value to set the AwardId
     */
    public void setAwardId(Number value) {
        setAttributeInternal(AWARDID, value);
    }

    /**
     * Gets the attribute value for ProfessorId, using the alias name ProfessorId.
     * @return the value of ProfessorId
     */
    public Number getProfessorId() {
        return (Number) getAttributeInternal(PROFESSORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProfessorId.
     * @param value value to set the ProfessorId
     */
    public void setProfessorId(Number value) {
        setAttributeInternal(PROFESSORID, value);
    }

    /**
     * @param awardProfessorId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number awardProfessorId) {
        return new Key(new Object[] { awardProfessorId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("oracle.adf.research.model.bc.entity.AwardProfessorEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq = new SequenceImpl("AWARD_PROFESSOR_SEQ",this.getDBTransaction());
        Number n = seq.getSequenceNumber();
        this.setAwardProfessorId(n);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

