package oracle.adf.research.model.bc.entity;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 15 00:58:56 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProfessorQualRelationEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ProfessorQualId,
        ProfessorId,
        QualId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PROFESSORQUALID = AttributesEnum.ProfessorQualId.index();
    public static final int PROFESSORID = AttributesEnum.ProfessorId.index();
    public static final int QUALID = AttributesEnum.QualId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProfessorQualRelationEOImpl() {
    }

    /**
     * Gets the attribute value for ProfessorQualId, using the alias name ProfessorQualId.
     * @return the value of ProfessorQualId
     */
    public Number getProfessorQualId() {
        return (Number) getAttributeInternal(PROFESSORQUALID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProfessorQualId.
     * @param value value to set the ProfessorQualId
     */
    public void setProfessorQualId(Number value) {
        setAttributeInternal(PROFESSORQUALID, value);
    }

    /**
     * Gets the attribute value for ProfessorId, using the alias name ProfessorId.
     * @return the value of ProfessorId
     */
    public Number getProfessorId() {
        return (Number) getAttributeInternal(PROFESSORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProfessorId.
     * @param value value to set the ProfessorId
     */
    public void setProfessorId(Number value) {
        setAttributeInternal(PROFESSORID, value);
    }

    /**
     * Gets the attribute value for QualId, using the alias name QualId.
     * @return the value of QualId
     */
    public Number getQualId() {
        return (Number) getAttributeInternal(QUALID);
    }

    /**
     * Sets <code>value</code> as the attribute value for QualId.
     * @param value value to set the QualId
     */
    public void setQualId(Number value) {
        setAttributeInternal(QUALID, value);
    }

    /**
     * @param professorQualId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number professorQualId) {
        return new Key(new Object[] { professorQualId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("oracle.adf.research.model.bc.entity.ProfessorQualRelationEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq = new SequenceImpl("PROFESSOR_QUAL_RELATION_SEQ",this.getDBTransaction());
        Number n = seq.getSequenceNumber();
        this.setProfessorQualId(n);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

