package oracle.adf.research.model.bc.entity;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 27 00:40:19 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VideosEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        VideoId,
        VideoContent,
        VideoName,
        Discription,
        CourseId,
        VideoPath,
        VideoUpload,
        Courses;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int VIDEOID = AttributesEnum.VideoId.index();
    public static final int VIDEOCONTENT = AttributesEnum.VideoContent.index();
    public static final int VIDEONAME = AttributesEnum.VideoName.index();
    public static final int DISCRIPTION = AttributesEnum.Discription.index();
    public static final int COURSEID = AttributesEnum.CourseId.index();
    public static final int VIDEOPATH = AttributesEnum.VideoPath.index();
    public static final int VIDEOUPLOAD = AttributesEnum.VideoUpload.index();
    public static final int COURSES = AttributesEnum.Courses.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VideosEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("oracle.adf.research.model.bc.entity.VideosEO");
    }


    /**
     * Gets the attribute value for VideoId, using the alias name VideoId.
     * @return the value of VideoId
     */
    public Number getVideoId() {
        return (Number) getAttributeInternal(VIDEOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VideoId.
     * @param value value to set the VideoId
     */
    public void setVideoId(Number value) {
        setAttributeInternal(VIDEOID, value);
    }

    /**
     * Gets the attribute value for VideoContent, using the alias name VideoContent.
     * @return the value of VideoContent
     */
    public BlobDomain getVideoContent() {
        return (BlobDomain) getAttributeInternal(VIDEOCONTENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for VideoContent.
     * @param value value to set the VideoContent
     */
    public void setVideoContent(BlobDomain value) {
        setAttributeInternal(VIDEOCONTENT, value);
    }

    /**
     * Gets the attribute value for VideoName, using the alias name VideoName.
     * @return the value of VideoName
     */
    public String getVideoName() {
        return (String) getAttributeInternal(VIDEONAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for VideoName.
     * @param value value to set the VideoName
     */
    public void setVideoName(String value) {
        setAttributeInternal(VIDEONAME, value);
    }

    /**
     * Gets the attribute value for Discription, using the alias name Discription.
     * @return the value of Discription
     */
    public String getDiscription() {
        return (String) getAttributeInternal(DISCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Discription.
     * @param value value to set the Discription
     */
    public void setDiscription(String value) {
        setAttributeInternal(DISCRIPTION, value);
    }

    /**
     * Gets the attribute value for CourseId, using the alias name CourseId.
     * @return the value of CourseId
     */
    public Number getCourseId() {
        return (Number) getAttributeInternal(COURSEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CourseId.
     * @param value value to set the CourseId
     */
    public void setCourseId(Number value) {
        setAttributeInternal(COURSEID, value);
    }

    /**
     * Gets the attribute value for VideoPath, using the alias name VideoPath.
     * @return the value of VideoPath
     */
    public String getVideoPath() {
        return (String) getAttributeInternal(VIDEOPATH);
    }

    /**
     * Sets <code>value</code> as the attribute value for VideoPath.
     * @param value value to set the VideoPath
     */
    public void setVideoPath(String value) {
        setAttributeInternal(VIDEOPATH, value);
    }

    /**
     * Gets the attribute value for VideoUpload, using the alias name VideoUpload.
     * @return the value of VideoUpload
     */
    public String getVideoUpload() {
        return (String) getAttributeInternal(VIDEOUPLOAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for VideoUpload.
     * @param value value to set the VideoUpload
     */
    public void setVideoUpload(String value) {
        setAttributeInternal(VIDEOUPLOAD, value);
    }

    /**
     * @return the associated entity CoursesEOImpl.
     */
    public CoursesEOImpl getCourses() {
        return (CoursesEOImpl) getAttributeInternal(COURSES);
    }

    /**
     * Sets <code>value</code> as the associated entity CoursesEOImpl.
     */
    public void setCourses(CoursesEOImpl value) {
        setAttributeInternal(COURSES, value);
    }


    /**
     * @param videoId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number videoId) {
        return new Key(new Object[] { videoId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_INSERT) {
            SequenceImpl seq = new SequenceImpl("VIDEOS_SEQ", this.getDBTransaction());
            Number video_id = seq.getSequenceNumber();
            this.setVideoId(video_id);
        }
        super.doDML(operation, e);
    }
}

