package oracle.adf.research.model.bc.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 27 00:51:38 EET 2018
// ---------------------------------------------------------------------
public interface CoursesAM extends ApplicationModule {
    Boolean checkCourseCode(String code);

    String courseCode();

    void defaultCoursess();
}

