package oracle.adf.research.model.bc.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 23 15:35:28 EET 2018
// ---------------------------------------------------------------------
public interface LibraryAM extends ApplicationModule {
    String bookCode();

    Boolean checkBookCode(String code);

    void defaultBooks();
}

