package oracle.adf.research.model.bc.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 11 20:09:33 EET 2018
// ---------------------------------------------------------------------
public interface ProfessorsAM extends ApplicationModule {
    void searchByName(String name);


    String acceptProfessor(String email);

    void filterApprovals();
}

